private ["_unit", "_tpl", "_fn_checktpl"];

_unit = _this select 0;
_tpl = toUpper (_this select 1);

if (!local _unit) exitWith {};

_fn_checktpl = {
	private ["_tpl","_unit"];
	_unit = _this select 0;
	_tpl = _this select 1;

	switch (_tpl) do {

case "SVOB_SER":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "MNP_CombatUniform_USMC_ST";
for "_i" from 1 to 2 do {_unit addItemToUniform "SmokeShell";};
for "_i" from 1 to 3 do {_unit addItemToUniform "Chemlight_green";};
for "_i" from 1 to 2 do {_unit addItemToUniform "SmokeShellYellow";};
for "_i" from 1 to 2 do {_unit addItemToUniform "SmokeShellRed";};
for "_i" from 1 to 2 do {_unit addItemToUniform "rhs_mag_30Rnd_556x45_Mk318_Stanag";};
_unit addVest "TRYK_V_tacv1";
for "_i" from 1 to 2 do {_unit addItemToVest "AGM_Morphine";};
for "_i" from 1 to 4 do {_unit addItemToVest "AGM_Bandage";};
for "_i" from 1 to 5 do {_unit addItemToVest "rhsusf_mag_7x45acp_MHP";};
for "_i" from 1 to 4 do {_unit addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {_unit addItemToVest "rhs_mag_30Rnd_556x45_Mk318_Stanag";};
_unit addHeadgear "MNP_Boonie_ASA";
_unit addGoggles "G_Balaclava_oli";
_unit addItem "rhs_mag_30Rnd_556x45_Mk318_Stanag";
_unit addItem "rhsusf_mag_7x45acp_MHP";
_unit addWeapon "rhs_weap_m4a1_carryhandle_grip";
_unit addPrimaryWeaponItem "UK3CB_BAF_LLM_Flashlight";
_unit addPrimaryWeaponItem "rhsusf_acc_eotech_552";
_unit addWeapon "rhsusf_weap_m1911a1";
_unit addWeapon "Binocular";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
_unit linkItem "TRYK_Shemagh_G_NV";
};

case "SVOB_F":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "MNP_CombatUniform_USMC_ST";
_unit addItemToUniform "UK3CB_BAF_30Rnd";
_unit addItemToUniform "rhsusf_mag_7x45acp_MHP";
for "_i" from 1 to 3 do {_unit addItemToUniform "HandGrenade";};
_unit addItemToUniform "Chemlight_green";
_unit addVest "TRYK_V_tacv1";
for "_i" from 1 to 2 do {_unit addItemToVest "AGM_Morphine";};
for "_i" from 1 to 4 do {_unit addItemToVest "AGM_Bandage";};
for "_i" from 1 to 2 do {_unit addItemToVest "UK3CB_BAF_30Rnd";};
for "_i" from 1 to 4 do {_unit addItemToVest "rhsusf_mag_7x45acp_MHP";};
for "_i" from 1 to 5 do {_unit addItemToVest "Chemlight_green";};
for "_i" from 1 to 2 do {_unit addItemToVest "SmokeShellGreen";};
_unit addBackpack "B_CDF_A3_Backpack";
_unit addGoggles "G_Balaclava_blk";
_unit addItem "UK3CB_BAF_30Rnd";
_unit addItem "rhsusf_mag_7x45acp_MHP";
_unit addWeapon "UK3CB_BAF_L85A2_RIS_AFG";
_unit addPrimaryWeaponItem "UK3CB_BAF_LLM_Flashlight";
_unit addPrimaryWeaponItem "iansky_specterdr";
_unit addWeapon "rhsusf_weap_m1911a1";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};


case "SVOB_SN":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "MNP_CombatUniform_USMC_ST";
_unit addItemToUniform "10Rnd_av_762x39_svd";
_unit addItemToUniform "30Rnd_9x21_Mag";
for "_i" from 1 to 3 do {_unit addItemToUniform "HandGrenade";};
_unit addVest "TRYK_V_tacv1";
for "_i" from 1 to 2 do {_unit addItemToVest "AGM_Morphine";};
for "_i" from 1 to 4 do {_unit addItemToVest "AGM_Bandage";};
_unit addItemToVest "AGM_Epipen";
for "_i" from 1 to 3 do {_unit addItemToVest "10Rnd_av_762x39_svd";};
for "_i" from 1 to 2 do {_unit addItemToVest "30Rnd_9x21_Mag";};
for "_i" from 1 to 2 do {_unit addItemToVest "SmokeShell";};
for "_i" from 1 to 6 do {_unit addItemToVest "Chemlight_green";};
_unit addItemToVest "APERSTripMine_Wire_Mag";
_unit addHeadgear "H_Watchcap_camo";
_unit addGoggles "G_Bandanna_oli";
_unit addItem "10Rnd_av_762x39_svd";
_unit addItem "30Rnd_9x21_Mag";
_unit addWeapon "av_svu_base";
_unit addPrimaryWeaponItem "optic_av_pso";
_unit addWeapon "arifle_av_sr22m";
_unit addWeapon "Binocular";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "SVOB_AT":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "MNP_CombatUniform_USMC_T";
for "_i" from 1 to 2 do {_unit addItemToUniform "HandGrenade";};
_unit addItemToUniform "SmokeShell";
_unit addItemToUniform "Chemlight_green";
for "_i" from 1 to 3 do {_unit addItemToUniform "rhs_mag_30Rnd_556x45_Mk318_Stanag";};
_unit addVest "TRYK_V_tacv1";
for "_i" from 1 to 7 do {_unit addItemToVest "rhsusf_mag_7x45acp_MHP";};
for "_i" from 1 to 2 do {_unit addItemToVest "HandGrenade";};
_unit addItemToVest "SmokeShell";
for "_i" from 1 to 2 do {_unit addItemToVest "Chemlight_green";};
for "_i" from 1 to 2 do {_unit addItemToVest "SmokeShellYellow";};
for "_i" from 1 to 2 do {_unit addItemToVest "SmokeShellRed";};
for "_i" from 1 to 3 do {_unit addItemToVest "rhs_mag_30Rnd_556x45_Mk318_Stanag";};
_unit addBackpack "B_FieldPack_oli";
for "_i" from 1 to 4 do {_unit addItemToBackpack "AGM_Bandage";};
for "_i" from 1 to 2 do {_unit addItemToBackpack "AGM_Morphine";};
for "_i" from 1 to 2 do {_unit addItemToBackpack "AGM_Epipen";};
for "_i" from 1 to 3 do {_unit addItemToBackpack "rhs_mag_30Rnd_556x45_Mk318_Stanag";};
_unit addHeadgear "Altyn";
_unit addGoggles "G_Bandanna_shades";
_unit addItem "rhs_mag_30Rnd_556x45_Mk318_Stanag";
_unit addItem "rhsusf_mag_7x45acp_MHP";
_unit addWeapon "rhs_weap_m4a1_carryhandle_grip2";
_unit addPrimaryWeaponItem "acc_flashlight";
_unit addPrimaryWeaponItem "rhsusf_acc_eotech_552";
_unit addWeapon "rhsusf_weap_m1911a1";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
_unit linkItem "TRYK_Shemagh_G_NV";
};

case "SVOB_MED":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "MNP_CombatUniform_USMC_T";
for "_i" from 1 to 2 do {_unit addItemToUniform "rhs_mag_30Rnd_556x45_Mk318_Stanag";};
for "_i" from 1 to 3 do {_unit addItemToUniform "HandGrenade";};
_unit addItemToUniform "SmokeShell";
_unit addVest "TRYK_V_tacv1";
for "_i" from 1 to 2 do {_unit addItemToVest "rhs_mag_30Rnd_556x45_Mk318_Stanag";};
for "_i" from 1 to 7 do {_unit addItemToVest "UK3CB_BAF_17Rnd_9mm";};
_unit addItemToVest "HandGrenade";
_unit addItemToVest "SmokeShell";
for "_i" from 1 to 3 do {_unit addItemToVest "Chemlight_green";};
for "_i" from 1 to 2 do {_unit addItemToVest "SmokeShellYellow";};
for "_i" from 1 to 2 do {_unit addItemToVest "SmokeShellRed";};
_unit addBackpack "B_Carryall_oli";
for "_i" from 1 to 22 do {_unit addItemToBackpack "AGM_Bandage";};
for "_i" from 1 to 16 do {_unit addItemToBackpack "AGM_Morphine";};
for "_i" from 1 to 3 do {_unit addItemToBackpack "AGM_Epipen";};
for "_i" from 1 to 6 do {_unit addItemToBackpack "AGM_Bloodbag";};
_unit addHeadgear "ZSH_1_zel";
_unit addGoggles "Mask_M40_OD";
_unit addItem "rhs_mag_30Rnd_556x45_Mk318_Stanag";
_unit addItem "UK3CB_BAF_17Rnd_9mm";
_unit addWeapon "rhs_weap_m16a4_carryhandle_grip_pmag";
_unit addPrimaryWeaponItem "UK3CB_BAF_LLM_Flashlight";
_unit addWeapon "UK3CB_BAF_L131A1";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
_unit linkItem "TRYK_Shemagh_G_NV";
};

case "SVOB_AR":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "MNP_CombatUniform_USMC_ST";
for "_i" from 1 to 3 do {_unit addItemToUniform "Chemlight_green";};
for "_i" from 1 to 2 do {_unit addItemToUniform "SmokeShellYellow";};
for "_i" from 1 to 2 do {_unit addItemToUniform "SmokeShellRed";};
for "_i" from 1 to 2 do {_unit addItemToUniform "HandGrenade";};
for "_i" from 1 to 2 do {_unit addItemToUniform "SmokeShell";};
_unit addVest "TRYK_V_tacv1";
_unit addItemToVest "rhs_200rnd_556x45_M_SAW";
for "_i" from 1 to 3 do {_unit addItemToVest "rhsusf_mag_7x45acp_MHP";};
for "_i" from 1 to 2 do {_unit addItemToVest "HandGrenade";};
_unit addBackpack "B_TacticalPack_oli";
for "_i" from 1 to 4 do {_unit addItemToBackpack "AGM_Morphine";};
for "_i" from 1 to 4 do {_unit addItemToBackpack "AGM_Bandage";};
for "_i" from 1 to 2 do {_unit addItemToBackpack "AGM_Epipen";};
for "_i" from 1 to 2 do {_unit addItemToBackpack "rhs_200rnd_556x45_M_SAW";};
_unit addHeadgear "Altyn";
_unit addGoggles "G_Balaclava_oli";
_unit addItem "rhs_200rnd_556x45_M_SAW";
_unit addItem "rhsusf_mag_7x45acp_MHP";
_unit addWeapon "rhs_weap_m249_pip_S_vfg";
_unit addPrimaryWeaponItem "UK3CB_BAF_LLM_Flashlight";
_unit addWeapon "rhsusf_weap_m1911a1";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "SVOB_GR":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "MNP_CombatUniform_USMC_T";
for "_i" from 1 to 3 do {_unit addItemToUniform "HandGrenade";};
_unit addItemToUniform "SmokeShell";
for "_i" from 1 to 2 do {_unit addItemToUniform "rhs_mag_30Rnd_556x45_Mk318_Stanag";};
_unit addVest "TRYK_V_tacv1";
_unit addItemToVest "HandGrenade";
_unit addItemToVest "SmokeShell";
for "_i" from 1 to 5 do {_unit addItemToVest "SmokeShellRed";};
for "_i" from 1 to 2 do {_unit addItemToVest "SmokeShellYellow";};
for "_i" from 1 to 2 do {_unit addItemToVest "rhs_mag_30Rnd_556x45_Mk318_Stanag";};
for "_i" from 1 to 4 do {_unit addItemToVest "rhs_mag_M441_HE";};
for "_i" from 1 to 7 do {_unit addItemToVest "11Rnd_45ACP_Mag";};
_unit addBackpack "TRYK_B_FieldPack_Wood";
for "_i" from 1 to 6 do {_unit addItemToBackpack "AGM_Bandage";};
for "_i" from 1 to 6 do {_unit addItemToBackpack "AGM_Morphine";};
for "_i" from 1 to 2 do {_unit addItemToBackpack "AGM_Epipen";};
_unit addHeadgear "ZSH_1_zel";
_unit addGoggles "TRYK_kio_balaclava_BLK";
_unit addItem "rhs_mag_30Rnd_556x45_Mk318_Stanag";
_unit addItem "rhs_mag_M441_HE";
_unit addItem "11Rnd_45ACP_Mag";
_unit addWeapon "rhs_weap_m4a1_carryhandle_m203";
_unit addPrimaryWeaponItem "UK3CB_BAF_LLM_Flashlight";
_unit addWeapon "hgun_Pistol_heavy_01_F";
_unit addWeapon "Binocular";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
_unit linkItem "TRYK_Shemagh_G_NV";
};






case "MERC_S":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "NatoU_Black";
for "_i" from 1 to 3 do {_unit addItemToUniform "rhs_mag_30Rnd_556x45_Mk318_Stanag";};
_unit addItemToUniform "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Yellow";
for "_i" from 1 to 4 do {_unit addItemToUniform "Chemlight_yellow";};
_unit addVest "V_PlateCarrier1_PMC_blk";
for "_i" from 1 to 2 do {_unit addItemToVest "AGM_Morphine";};
for "_i" from 1 to 4 do {_unit addItemToVest "AGM_Bandage";};
for "_i" from 1 to 7 do {_unit addItemToVest "UK3CB_BAF_17Rnd_9mm";};
for "_i" from 1 to 2 do {_unit addItemToVest "Chemlight_yellow";};
for "_i" from 1 to 2 do {_unit addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {_unit addItemToVest "SmokeShellYellow";};
_unit addHeadgear "TRYK_H_PASGT_BLK";
_unit addGoggles "G_Balaclava_blk";
_unit addItem "rhs_mag_30Rnd_556x45_Mk318_Stanag";
_unit addItem "UK3CB_BAF_17Rnd_9mm";
_unit addWeapon "rhs_weap_m4a1_carryhandle_grip";
_unit addPrimaryWeaponItem "rhsusf_acc_anpeq15_light";
_unit addWeapon "UK3CB_BAF_L131A1";
_unit addHandgunItem "muzzle_snds_L";
_unit addWeapon "Binocular";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "MERC_SP":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "NatoU_Black";
for "_i" from 1 to 3 do {_unit addItemToUniform "10Rnd_av_762x39_svd";};
_unit addItemToUniform "HandGrenade";
_unit addVest "V_PlateCarrier2_blk";
for "_i" from 1 to 2 do {_unit addItemToVest "AGM_Morphine";};
for "_i" from 1 to 4 do {_unit addItemToVest "AGM_Bandage";};
_unit addItemToVest "10Rnd_av_762x39_svd";
for "_i" from 1 to 6 do {_unit addItemToVest "16Rnd_9x21_Mag";};
_unit addItemToVest "HandGrenade";
for "_i" from 1 to 2 do {_unit addItemToVest "SmokeShellYellow";};
for "_i" from 1 to 6 do {_unit addItemToVest "Chemlight_yellow";};
_unit addHeadgear "H_Bandanna_gry";
_unit addGoggles "G_Bandanna_blk";
_unit addItem "10Rnd_av_762x39_svd";
_unit addItem "16Rnd_9x21_Mag";
_unit addWeapon "av_svu_base";
_unit addPrimaryWeaponItem "optic_av_pso";
_unit addWeapon "hgun_Rook40_F";
_unit addHandgunItem "muzzle_snds_L";
_unit addWeapon "Binocular";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
_unit linkItem "TRYK_TAC_boonie_SET_NV";
};

case "MERC_GR":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "NatoU_Black";
for "_i" from 1 to 3 do {_unit addItemToUniform "30Rnd_ak_545x39_mag";};
for "_i" from 1 to 2 do {_unit addItemToUniform "1Rnd_HE_Grenade_shell";};
_unit addItemToUniform "Chemlight_yellow";
_unit addVest "TacVest_black";
for "_i" from 1 to 2 do {_unit addItemToVest "AGM_Morphine";};
for "_i" from 1 to 4 do {_unit addItemToVest "AGM_Bandage";};
_unit addItemToVest "AGM_Epipen";
for "_i" from 1 to 2 do {_unit addItemToVest "1Rnd_HE_Grenade_shell";};
for "_i" from 1 to 8 do {_unit addItemToVest "20Rnd_9x21_Mag";};
for "_i" from 1 to 2 do {_unit addItemToVest "HandGrenade";};
for "_i" from 1 to 5 do {_unit addItemToVest "Chemlight_yellow";};
_unit addBackpack "B_AssaultPack_blk";
for "_i" from 1 to 2 do {_unit addItemToBackpack "SmokeShellYellow";};
_unit addGoggles "G_Balaclava_blk";
_unit addItem "30Rnd_ak_545x39_mag";
_unit addItem "1Rnd_HE_Grenade_shell";
_unit addItem "20Rnd_9x21_Mag";
_unit addWeapon "arifle_av_aekg";
_unit addWeapon "av_aps";
_unit addHandgunItem "muzzle_snds_L";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "MERC_AT":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "NatoU_Black";
_unit addItemToUniform "UK3CB_BAF_30Rnd";
for "_i" from 1 to 5 do {_unit addItemToUniform "8Rnd_Mag";};
_unit addVest "TRYK_V_tacv1M_BK";
for "_i" from 1 to 2 do {_unit addItemToVest "AGM_Morphine";};
for "_i" from 1 to 4 do {_unit addItemToVest "AGM_Bandage";};
_unit addItemToVest "AGM_Epipen";
for "_i" from 1 to 2 do {_unit addItemToVest "UK3CB_BAF_30Rnd";};
for "_i" from 1 to 6 do {_unit addItemToVest "Chemlight_yellow";};
for "_i" from 1 to 2 do {_unit addItemToVest "SmokeShellYellow";};
for "_i" from 1 to 2 do {_unit addItemToVest "HandGrenade";};
_unit addBackpack "B_AssaultPack_blk";
_unit addGoggles "G_Balaclava_blk";
_unit addItem "UK3CB_BAF_30Rnd";
_unit addItem "rhs_rpg7_PG7VL_mag";
_unit addItem "8Rnd_Mag";
_unit addWeapon "UK3CB_BAF_L85A2_EMAG";
_unit addPrimaryWeaponItem "iansky_specterdr";
_unit addWeapon "rhs_weap_rpg7";
_unit addWeapon "av_tt";
_unit addWeapon "Binocular";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "MERC_F":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "NatoU_Black";
for "_i" from 1 to 3 do {_unit addItemToUniform "30Rnd_ak_545x39_mag";};
_unit addItemToUniform "HandGrenade";
_unit addVest "TacVest_black";
for "_i" from 1 to 2 do {_unit addItemToVest "AGM_Morphine";};
for "_i" from 1 to 4 do {_unit addItemToVest "AGM_Bandage";};
for "_i" from 1 to 2 do {_unit addItemToVest "AGM_Epipen";};
for "_i" from 1 to 7 do {_unit addItemToVest "16Rnd_9x21_Mag";};
_unit addItemToVest "HandGrenade";
for "_i" from 1 to 2 do {_unit addItemToVest "SmokeShellYellow";};
for "_i" from 1 to 6 do {_unit addItemToVest "Chemlight_yellow";};
_unit addBackpack "PMC_AssaultPack_Blk";
_unit addHeadgear "TRYK_H_PASGT_BLK";
_unit addGoggles "Mask_M50";
_unit addItem "30Rnd_ak_545x39_mag";
_unit addItem "16Rnd_9x21_Mag";
_unit addWeapon "arifle_av_aks74";
_unit addWeapon "hgun_Rook40_F";
_unit addHandgunItem "muzzle_snds_L";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
_unit linkItem "TRYK_balaclava_BLACK_NV";
};

case "MERC_AR":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "NatoU_Black";
for "_i" from 1 to 2 do {_unit addItemToUniform "HandGrenade";};
for "_i" from 1 to 6 do {_unit addItemToUniform "Chemlight_yellow";};
for "_i" from 1 to 2 do {_unit addItemToUniform "SmokeShellYellow";};
_unit addVest "TRYK_V_tacv1M_BK";
for "_i" from 1 to 2 do {_unit addItemToVest "AGM_Morphine";};
for "_i" from 1 to 4 do {_unit addItemToVest "AGM_Bandage";};
_unit addItemToVest "AGM_Epipen";
for "_i" from 1 to 3 do {_unit addItemToVest "rhsusf_100Rnd_556x45_soft_pouch";};
_unit addBackpack "B_AssaultPack_blk";
_unit addHeadgear "H_Watchcap_blk";
_unit addGoggles "Mask_M40";
_unit addItem "rhsusf_100Rnd_556x45_soft_pouch";
_unit addWeapon "rhs_weap_m249_pip_S";
_unit addPrimaryWeaponItem "UK3CB_BAF_LLM_Flashlight";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "MERC_MED":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "NatoU_Black";
for "_i" from 1 to 6 do {_unit addItemToUniform "8Rnd_SA_12Gauge_Pellets";};
_unit addItemToUniform "20Rnd_9x21_Mag";
for "_i" from 1 to 2 do {_unit addItemToUniform "SmokeShellYellow";};
_unit addItemToUniform "Chemlight_yellow";
_unit addVest "V_PlateCarrier1_PMC_blk";
for "_i" from 1 to 6 do {_unit addItemToVest "20Rnd_9x21_Mag";};
for "_i" from 1 to 5 do {_unit addItemToVest "Chemlight_yellow";};
for "_i" from 1 to 2 do {_unit addItemToVest "HandGrenade";};
_unit addBackpack "PMC_AssaultPack_Blk";
for "_i" from 1 to 10 do {_unit addItemToBackpack "AGM_Bandage";};
for "_i" from 1 to 10 do {_unit addItemToBackpack "AGM_Morphine";};
for "_i" from 1 to 4 do {_unit addItemToBackpack "AGM_Epipen";};
for "_i" from 1 to 4 do {_unit addItemToBackpack "AGM_Bloodbag";};
_unit addHeadgear "TRYK_H_PASGT_BLK";
_unit addGoggles "Mask_M50";
_unit addItem "8Rnd_SA_12Gauge_Pellets";
_unit addItem "20Rnd_9x21_Mag";
_unit addWeapon "prifle_SA_MP153";
_unit addWeapon "av_aps_sd";
_unit addHandgunItem "muzzle_snds_L";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
_unit linkItem "TRYK_balaclava_BLACK_NV";
};





case "BAND_S":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "TRYK_U_denim_hood_blk";
_unit addItemToUniform "30Rnd_ak_545x39_mag";
for "_i" from 1 to 2 do {_unit addItemToUniform "HandGrenade";};
for "_i" from 1 to 5 do {_unit addItemToUniform "Chemlight_blue";};
_unit addVest "TacVest_black";
for "_i" from 1 to 2 do {_unit addItemToVest "AGM_Morphine";};
for "_i" from 1 to 4 do {_unit addItemToVest "AGM_Bandage";};
for "_i" from 1 to 2 do {_unit addItemToVest "30Rnd_ak_545x39_mag";};
for "_i" from 1 to 8 do {_unit addItemToVest "8Rnd_Mag_pm";};
for "_i" from 1 to 2 do {_unit addItemToVest "rhs_mag_rdg2_white";};
_unit addBackpack "TRYK_B_Belt_BLK";
_unit addGoggles "G_Balaclava_blk";
_unit addItem "30Rnd_ak_545x39_mag";
_unit addItem "8Rnd_Mag_pm";
_unit addWeapon "arifle_av_aksu";
_unit addWeapon "av_makarov";
_unit addWeapon "Binocular";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "BAND_SN":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "TRYK_U_B_PCUODs";
for "_i" from 1 to 3 do {_unit addItemToUniform "20Rnd_av_9x39mm_SP5";};
for "_i" from 1 to 3 do {_unit addItemToUniform "Chemlight_blue";};
_unit addVest "V_BandollierB_blk";
for "_i" from 1 to 4 do {_unit addItemToVest "AGM_Morphine";};
for "_i" from 1 to 6 do {_unit addItemToVest "AGM_Bandage";};
for "_i" from 1 to 3 do {_unit addItemToVest "rhs_mag_9x18_12_57N181S";};
_unit addItemToVest "20Rnd_av_9x39mm_SP5";
_unit addGoggles "G_Balaclava_blk";
_unit addItem "20Rnd_av_9x39mm_SP5";
_unit addItem "rhs_mag_9x18_12_57N181S";
_unit addWeapon "arifle_av_asval";
_unit addPrimaryWeaponItem "optic_av_pso";
_unit addWeapon "rhs_weap_makarov_pmm";
_unit addWeapon "Binocular";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "BAND_MED":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "TRYK_U_denim_hood_mc";
for "_i" from 1 to 6 do {_unit addItemToUniform "AGM_CableTie";};
for "_i" from 1 to 2 do {_unit addItemToUniform "8Rnd_SA_12Gauge_Pellets";};
for "_i" from 1 to 2 do {_unit addItemToUniform "HandGrenade";};
for "_i" from 1 to 3 do {_unit addItemToUniform "Chemlight_blue";};
_unit addVest "V_TacVest_darkblck";
_unit addItemToVest "AGM_CableTie";
for "_i" from 1 to 7 do {_unit addItemToVest "8Rnd_SA_12Gauge_Pellets";};
for "_i" from 1 to 9 do {_unit addItemToVest "8Rnd_Mag_pm";};
_unit addBackpack "TRYK_B_Belt_CYT";
for "_i" from 1 to 10 do {_unit addItemToBackpack "AGM_Morphine";};
for "_i" from 1 to 16 do {_unit addItemToBackpack "AGM_Bandage";};
_unit addGoggles "G_Balaclava_blk";
_unit addItem "8Rnd_SA_12Gauge_Pellets";
_unit addItem "8Rnd_Mag_pm";
_unit addWeapon "prifle_SA_MP153";
_unit addWeapon "av_makarov";
_unit addWeapon "Binocular";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "BAND_AT":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "TRYK_U_denim_hood_blk";
_unit addItemToUniform "30Rnd_ak_545x39_mag";
for "_i" from 1 to 2 do {_unit addItemToUniform "HandGrenade";};
for "_i" from 1 to 3 do {_unit addItemToUniform "Chemlight_blue";};
_unit addVest "V_BandollierB_blk";
_unit addBackpack "TRYK_B_Belt_BLK";
for "_i" from 1 to 3 do {_unit addItemToBackpack "30Rnd_ak_545x39_mag";};
for "_i" from 1 to 9 do {_unit addItemToBackpack "8Rnd_Mag_pm";};
_unit addGoggles "G_Balaclava_blk";
_unit addItem "30Rnd_ak_545x39_mag";
_unit addItem "8Rnd_Mag_pm";
_unit addWeapon "arifle_av_aksu";
_unit addWeapon "av_makarov";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "BAND_GR":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "TRYK_U_denim_hood_nc";
_unit addItemToUniform "rhs_30Rnd_762x39mm";
_unit addItemToUniform "rhs_VOG25";
for "_i" from 1 to 2 do {_unit addItemToUniform "HandGrenade";};
for "_i" from 1 to 3 do {_unit addItemToUniform "Chemlight_blue";};
_unit addVest "V_Chestrig_blk";
for "_i" from 1 to 2 do {_unit addItemToVest "AGM_Morphine";};
for "_i" from 1 to 4 do {_unit addItemToVest "AGM_Bandage";};
for "_i" from 1 to 2 do {_unit addItemToVest "rhs_30Rnd_762x39mm";};
for "_i" from 1 to 2 do {_unit addItemToVest "rhs_VOG25";};
for "_i" from 1 to 2 do {_unit addItemToVest "rhs_VG40OP_red";};
for "_i" from 1 to 9 do {_unit addItemToVest "8Rnd_Mag_pm";};
_unit addBackpack "TRYK_B_Belt_BLK";
_unit addHeadgear "TRYK_R_CAP_BLK";
_unit addGoggles "G_Bandanna_beast";
_unit addItem "rhs_30Rnd_762x39mm";
_unit addItem "rhs_VOG25";
_unit addItem "8Rnd_Mag_pm";
_unit addWeapon "rhs_weap_akms_gp25";
_unit addWeapon "av_makarov";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "BAND_AR":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "TRYK_U_hood_mc";
for "_i" from 1 to 4 do {_unit addItemToUniform "5Rnd_SA_762x54_Bullets";};
for "_i" from 1 to 3 do {_unit addItemToUniform "Chemlight_blue";};
_unit addItemToUniform "HandGrenade";
for "_i" from 1 to 2 do {_unit addItemToUniform "SmokeShell";};
_unit addVest "V_BandollierB_blk";
for "_i" from 1 to 4 do {_unit addItemToVest "AGM_Bandage";};
for "_i" from 1 to 2 do {_unit addItemToVest "AGM_Morphine";};
for "_i" from 1 to 7 do {_unit addItemToVest "5Rnd_SA_762x54_Bullets";};
for "_i" from 1 to 6 do {_unit addItemToVest "8Rnd_Mag_pm";};
_unit addBackpack "TRYK_B_Belt";
for "_i" from 1 to 3 do {_unit addItemToBackpack "8Rnd_Mag_pm";};
_unit addHeadgear "TRYK_R_CAP_BLK";
_unit addItem "5Rnd_SA_762x54_Bullets";
_unit addItem "8Rnd_Mag_pm";
_unit addWeapon "prifle_SA_Mosin";
_unit addWeapon "av_makarov";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
_unit linkItem "TRYK_G_Shades_Black_NV";
};

case "BAND_F":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "TRYK_U_denim_jersey_blk";
for "_i" from 1 to 3 do {_unit addItemToUniform "Chemlight_blue";};
for "_i" from 1 to 6 do {_unit addItemToUniform "rhsusf_5Rnd_00Buck";};
_unit addVest "V_BandollierB_blk";
for "_i" from 1 to 4 do {_unit addItemToVest "AGM_Morphine";};
for "_i" from 1 to 6 do {_unit addItemToVest "AGM_Bandage";};
for "_i" from 1 to 3 do {_unit addItemToVest "rhs_mag_9x18_12_57N181S";};
for "_i" from 1 to 4 do {_unit addItemToBackpack "30Rnd_ak_545x39_mag";};
_unit addHeadgear "H_Bandanna_gry";
_unit addGoggles "G_Bandanna_shades";
_unit addItem "rhsusf_5Rnd_00Buck";
_unit addItem "rhs_mag_9x18_12_57N181S";
_unit addWeapon "arifle_av_aksu";
_unit addWeapon "rhs_weap_makarov_pmm";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};




case "STALKER_S":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "CamoU_atacs";
_unit addItemToUniform "rhs_mag_rgd5";
for "_i" from 1 to 2 do {_unit addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {_unit addItemToUniform "Chemlight_green";};
for "_i" from 1 to 2 do {_unit addItemToUniform "30Rnd_ak_545x39_mag";};
_unit addVest "AAFVest01_h_green";
for "_i" from 1 to 4 do {_unit addItemToVest "AGM_Bandage";};
for "_i" from 1 to 2 do {_unit addItemToVest "AGM_Morphine";};
for "_i" from 1 to 8 do {_unit addItemToVest "rhs_mag_9x18_12_57N181S";};
for "_i" from 1 to 4 do {_unit addItemToVest "Chemlight_green";};
_unit addItemToVest "30Rnd_ak_545x39_mag";
_unit addHeadgear "ZSH";
_unit addGoggles "None";
_unit addItem "30Rnd_ak_545x39_mag";
_unit addItem "rhs_mag_9x18_12_57N181S";
_unit addWeapon "arifle_av_ak74old";
_unit addWeapon "rhs_weap_makarov_pmm";
_unit addWeapon "Binocular";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "STALKER_BF":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "CamoU_tan";
_unit addItemToUniform "rhs_30Rnd_545x39_AK";
for "_i" from 1 to 2 do {_unit addItemToUniform "rhs_mag_rgd5";};
for "_i" from 1 to 2 do {_unit addItemToUniform "SmokeShell";};
for "_i" from 1 to 3 do {_unit addItemToUniform "Chemlight_green";};
_unit addVest "AAFVest01_green";
for "_i" from 1 to 2 do {_unit addItemToVest "AGM_Morphine";};
for "_i" from 1 to 4 do {_unit addItemToVest "AGM_Bandage";};
for "_i" from 1 to 2 do {_unit addItemToVest "rhs_30Rnd_545x39_AK";};
for "_i" from 1 to 9 do {_unit addItemToVest "8Rnd_Mag";};
for "_i" from 1 to 3 do {_unit addItemToVest "Chemlight_green";};
_unit addHeadgear "ZSH_ochki";
_unit addItem "rhs_30Rnd_545x39_AK";
_unit addItem "8Rnd_Mag";
_unit addWeapon "rhs_weap_ak74m_2mag";
_unit addPrimaryWeaponItem "rhs_acc_dtk";
_unit addWeapon "av_tt";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "STALKER_1":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "CamoU_tan";
for "_i" from 1 to 3 do {_unit addItemToUniform "rhs_mag_rgd5";};
for "_i" from 1 to 2 do {_unit addItemToUniform "SmokeShellGreen";};
for "_i" from 1 to 5 do {_unit addItemToUniform "Chemlight_green";};
_unit addVest "TacVest_black";
for "_i" from 1 to 4 do {_unit addItemToVest "30Rnd_ak_545x39_mag";};
for "_i" from 1 to 5 do {_unit addItemToVest "8Rnd_Mag_pm";};
_unit addItemToVest "Chemlight_green";
_unit addBackpack "rhs_sidor";
for "_i" from 1 to 4 do {_unit addItemToBackpack "AGM_Bandage";};
for "_i" from 1 to 2 do {_unit addItemToBackpack "AGM_Morphine";};
_unit addItemToBackpack "AGM_Epipen";
_unit addHeadgear "rhs_tsh4";
_unit addGoggles "G_Bandanna_tan";
_unit addItem "30Rnd_ak_545x39_mag";
_unit addItem "8Rnd_Mag_pm";
_unit addWeapon "arifle_av_aksu_a";
_unit addPrimaryWeaponItem "av_kobra";
_unit addWeapon "av_makarov";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "STALKER_GR":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "CamoU_tan";
_unit addItemToUniform "30Rnd_av_762x39_mag";
_unit addItemToUniform "rhs_VOG25";
for "_i" from 1 to 2 do {_unit addItemToUniform "rhs_mag_rgd5";};
for "_i" from 1 to 2 do {_unit addItemToUniform "SmokeShellGreen";};
for "_i" from 1 to 2 do {_unit addItemToUniform "Chemlight_green";};
_unit addVest "AAFVest01_Kamysh";
for "_i" from 1 to 4 do {_unit addItemToVest "AGM_Bandage";};
_unit addItemToVest "AGM_Morphine";
for "_i" from 1 to 2 do {_unit addItemToVest "30Rnd_av_762x39_mag";};
for "_i" from 1 to 2 do {_unit addItemToVest "rhs_VOG25";};
for "_i" from 1 to 6 do {_unit addItemToVest "8Rnd_Mag";};
for "_i" from 1 to 3 do {_unit addItemToVest "rhs_GRD40_White";};
for "_i" from 1 to 2 do {_unit addItemToVest "rhs_VG40OP_white";};
for "_i" from 1 to 3 do {_unit addItemToVest "Chemlight_green";};
_unit addBackpack "B_Kitbag_rgr";
_unit addItemToBackpack "AGM_Morphine";
for "_i" from 1 to 2 do {_unit addItemToBackpack "rhs_VG40OP_white";};
for "_i" from 1 to 3 do {_unit addItemToBackpack "rhs_VG40OP_green";};
_unit addItemToBackpack "8Rnd_Mag";
_unit addHeadgear "BoonieH_flora";
_unit addItem "30Rnd_av_762x39_mag";
_unit addItem "rhs_VOG25";
_unit addItem "8Rnd_Mag";
_unit addWeapon "arifle_av_groza_gp";
_unit addWeapon "av_tt";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "STALKER_MED":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "CamoU_green";
for "_i" from 1 to 2 do {_unit addItemToUniform "8Rnd_SA_12Gauge_Pellets";};
_unit addItemToUniform "rhs_mag_rgd5";
for "_i" from 1 to 3 do {_unit addItemToUniform "SmokeShellGreen";};
for "_i" from 1 to 6 do {_unit addItemToUniform "Chemlight_green";};
_unit addVest "V_I_G_resistanceLeader_F";
for "_i" from 1 to 5 do {_unit addItemToVest "8Rnd_SA_12Gauge_Pellets";};
for "_i" from 1 to 6 do {_unit addItemToVest "8Rnd_Mag_pm";};
_unit addBackpack "B_Kitbag_rgr";
for "_i" from 1 to 10 do {_unit addItemToBackpack "AGM_Bandage";};
for "_i" from 1 to 10 do {_unit addItemToBackpack "AGM_Morphine";};
for "_i" from 1 to 6 do {_unit addItemToBackpack "AGM_Epipen";};
for "_i" from 1 to 6 do {_unit addItemToBackpack "AGM_Bloodbag";};
_unit addHeadgear "H_Booniehat_khk";
_unit addItem "8Rnd_SA_12Gauge_Pellets";
_unit addItem "8Rnd_Mag_pm";
_unit addWeapon "prifle_SA_MP153";
_unit addWeapon "av_makarov";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "STALKER_AR":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "CamoU_tan";
for "_i" from 1 to 2 do {_unit addItemToUniform "20Rnd_9x21_Mag";};
_unit addItemToUniform "rhs_mag_rgd5";
for "_i" from 1 to 2 do {_unit addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {_unit addItemToUniform "Chemlight_green";};
_unit addVest "AAFVest01_green";
for "_i" from 1 to 4 do {_unit addItemToVest "AGM_Bandage";};
for "_i" from 1 to 2 do {_unit addItemToVest "AGM_Morphine";};
_unit addItemToVest "rhs_100Rnd_762x54mmR";
for "_i" from 1 to 6 do {_unit addItemToVest "20Rnd_9x21_Mag";};
for "_i" from 1 to 4 do {_unit addItemToVest "Chemlight_green";};
_unit addBackpack "rhs_sidor";
_unit addItemToBackpack "rhs_100Rnd_762x54mmR";
_unit addHeadgear "H_Cap_oli";
_unit addGoggles "Mask_M40_OD";
_unit addItem "rhs_100Rnd_762x54mmR";
_unit addItem "20Rnd_9x21_Mag";
_unit addWeapon "rhs_weap_pkm";
_unit addWeapon "av_aps";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};


case "STALKER_F":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "CamoU_green";
for "_i" from 1 to 2 do {_unit addItemToUniform "rhs_mag_rgd5";};
for "_i" from 1 to 2 do {_unit addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {_unit addItemToUniform "Chemlight_green";};
for "_i" from 1 to 2 do {_unit addItemToUniform "8Rnd_Mag";};
_unit addVest "AAFVest01_mdu93";
for "_i" from 1 to 7 do {_unit addItemToVest "8Rnd_Mag";};
for "_i" from 1 to 3 do {_unit addItemToVest "20Rnd_av_9x39mm_SP5";};
_unit addHeadgear "TRYK_H_woolhat";
_unit addGoggles "G_Bandanna_blk";
_unit addItem "20Rnd_av_9x39mm_SP5";
_unit addItem "8Rnd_Mag";
_unit addWeapon "arifle_av_vss";
_unit addPrimaryWeaponItem "acc_flashlight";
_unit addPrimaryWeaponItem "optic_av_pso";
_unit addWeapon "av_tt";
_unit addWeapon "Binocular";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};










case "MONOLIT_S":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "45KO_u3_grey_camo_uniform";
_unit addItemToUniform "HandGrenade";
_unit addItemToUniform "SmokeShellYellow";
for "_i" from 1 to 6 do {_unit addItemToUniform "Chemlight_yellow";};
_unit addItemToUniform "rhs_mag_9x18_12_57N181S";
_unit addVest "TRYK_V_tacv10_OD";
for "_i" from 1 to 2 do {_unit addItemToVest "AGM_Morphine";};
for "_i" from 1 to 4 do {_unit addItemToVest "AGM_Bandage";};
for "_i" from 1 to 3 do {_unit addItemToVest "90Rnd_av_762x39_mag";};
for "_i" from 1 to 7 do {_unit addItemToVest "rhs_mag_9x18_12_57N181S";};
_unit addHeadgear "TIG";
_unit addGoggles "TRYK_kio_balaclava_BLK";
_unit addItem "90Rnd_av_762x39_mag";
_unit addItem "rhs_mag_9x18_12_57N181S";
_unit addWeapon "arifle_ak_sf";
_unit addPrimaryWeaponItem "acc_flashlight";
_unit addPrimaryWeaponItem "optic_av_aimp";
_unit addWeapon "rhs_weap_makarov_pmm";
_unit addWeapon "Binocular";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "MONOLIT_AR":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "45KO_u3_grey_camo_uniform";
for "_i" from 1 to 2 do {_unit addItemToUniform "HandGrenade";};
for "_i" from 1 to 2 do {_unit addItemToUniform "SmokeShellYellow";};
for "_i" from 1 to 6 do {_unit addItemToUniform "Chemlight_yellow";};
_unit addVest "TRYK_V_tacv10_OD";
for "_i" from 1 to 7 do {_unit addItemToVest "rhs_mag_9x18_12_57N181S";};
_unit addItemToVest "rhs_200rnd_556x45_M_SAW";
_unit addBackpack "B_FieldPack_cbr";
for "_i" from 1 to 2 do {_unit addItemToBackpack "AGM_Morphine";};
for "_i" from 1 to 4 do {_unit addItemToBackpack "AGM_Bandage";};
_unit addItemToBackpack "rhs_mag_9x18_12_57N181S";
_unit addHeadgear "TIG";
_unit addGoggles "Mask_M40";
_unit addItem "rhs_200rnd_556x45_M_SAW";
_unit addItem "rhs_mag_9x18_12_57N181S";
_unit addWeapon "rhs_weap_m249_pip_S_para";
_unit addPrimaryWeaponItem "UK3CB_BAF_LLM_Flashlight";
_unit addWeapon "rhs_weap_makarov_pmm";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "MONOLIT_GR":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "45KO_u3_grey_camo_uniform";
for "_i" from 1 to 2 do {_unit addItemToUniform "rhs_VOG25";};
for "_i" from 1 to 2 do {_unit addItemToUniform "HandGrenade";};
for "_i" from 1 to 2 do {_unit addItemToUniform "SmokeShellYellow";};
for "_i" from 1 to 2 do {_unit addItemToUniform "Chemlight_yellow";};
_unit addVest "TRYK_V_tacv10_OD";
for "_i" from 1 to 3 do {_unit addItemToVest "30Rnd_av_762x39_mag";};
_unit addItemToVest "rhs_VOG25";
for "_i" from 1 to 7 do {_unit addItemToVest "16Rnd_9x21_Mag";};
for "_i" from 1 to 4 do {_unit addItemToVest "Chemlight_yellow";};
_unit addBackpack "B_FieldPack_cbr";
for "_i" from 1 to 4 do {_unit addItemToBackpack "AGM_Bandage";};
for "_i" from 1 to 2 do {_unit addItemToBackpack "AGM_Morphine";};
_unit addHeadgear "TIG";
_unit addGoggles "G_Balaclava_blk";
_unit addItem "30Rnd_av_762x39_mag";
_unit addItem "rhs_VOG25";
_unit addItem "16Rnd_9x21_Mag";
_unit addWeapon "arifle_av_groza_gp";
_unit addWeapon "hgun_Rook40_F";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "MONOLIT_AT":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "45KO_u3_grey_camo_uniform";
_unit addItemToUniform "64Rnd_9x19_mag";
for "_i" from 1 to 2 do {_unit addItemToUniform "HandGrenade";};
for "_i" from 1 to 2 do {_unit addItemToUniform "SmokeShellYellow";};
_unit addItemToUniform "Chemlight_yellow";
_unit addVest "TRYK_V_tacv10_OD";
for "_i" from 1 to 2 do {_unit addItemToVest "64Rnd_9x19_mag";};
for "_i" from 1 to 7 do {_unit addItemToVest "rhs_mag_9x18_12_57N181S";};
for "_i" from 1 to 2 do {_unit addItemToVest "APERSTripMine_Wire_Mag";};
for "_i" from 1 to 5 do {_unit addItemToVest "Chemlight_yellow";};
_unit addBackpack "B_FieldPack_cbr";
_unit addItemToBackpack "rhs_mag_9x18_12_57N181S";
_unit addHeadgear "TIG";
_unit addGoggles "Mask_M40";
_unit addItem "64Rnd_9x19_mag";
_unit addItem "rhs_mag_9x18_12_57N181S";
_unit addWeapon "arifle_av_bizon";
_unit addPrimaryWeaponItem "muzzle_av_snds";
_unit addWeapon "rhs_weap_makarov_pmm";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "MONOLIT_MED":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "45KO_u3_grey_camo_uniform";
for "_i" from 1 to 2 do {_unit addItemToUniform "HandGrenade";};
for "_i" from 1 to 2 do {_unit addItemToUniform "SmokeShellYellow";};
for "_i" from 1 to 5 do {_unit addItemToUniform "Chemlight_yellow";};
_unit addVest "TRYK_V_tacv10_OD";
for "_i" from 1 to 3 do {_unit addItemToVest "UK3CB_BAF_30Rnd";};
for "_i" from 1 to 9 do {_unit addItemToVest "rhs_mag_9x19_17";};
_unit addBackpack "B_FieldPack_cbr";
for "_i" from 1 to 10 do {_unit addItemToBackpack "AGM_Morphine";};
for "_i" from 1 to 20 do {_unit addItemToBackpack "AGM_Bandage";};
for "_i" from 1 to 4 do {_unit addItemToBackpack "AGM_Epipen";};
for "_i" from 1 to 4 do {_unit addItemToBackpack "AGM_Bloodbag";};
_unit addHeadgear "TIG";
_unit addGoggles "Mask_M40";
_unit addItem "UK3CB_BAF_30Rnd";
_unit addItem "rhs_mag_9x19_17";
_unit addWeapon "UK3CB_BAF_L85A2_EMAG";
_unit addPrimaryWeaponItem "iansky_specterdr";
_unit addWeapon "rhs_weap_pya";
_unit addWeapon "Binocular";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};
case "MONOLIT_SN":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "45KO_u3_grey_camo_uniform";
for "_i" from 1 to 2 do {_unit addItemToUniform "HandGrenade";};
_unit addItemToUniform "Chemlight_yellow";
_unit addItemToUniform "5Rnd_127x108_Mag";
_unit addVest "TRYK_V_tacv10_OD";
for "_i" from 1 to 4 do {_unit addItemToVest "AGM_Bandage";};
for "_i" from 1 to 2 do {_unit addItemToVest "AGM_Morphine";};
for "_i" from 1 to 2 do {_unit addItemToVest "SmokeShellYellow";};
_unit addItemToVest "Chemlight_yellow";
_unit addItemToVest "APERSTripMine_Wire_Mag";
for "_i" from 1 to 3 do {_unit addItemToVest "5Rnd_127x108_Mag";};
for "_i" from 1 to 3 do {_unit addItemToVest "30Rnd_9x21_Mag";};
_unit addGoggles "G_Balaclava_blk";
_unit addItem "5Rnd_127x108_Mag";
_unit addItem "30Rnd_9x21_Mag";
_unit addWeapon "av_ksvk_base";
_unit addPrimaryWeaponItem "optic_av_pso";
_unit addWeapon "av_pp2000";
_unit addWeapon "Binocular";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "MONOLIT_F":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "45KO_u3_grey_camo_uniform";
_unit addItemToUniform "HandGrenade";
_unit addItemToUniform "SmokeShellYellow";
_unit addItemToUniform "Chemlight_yellow";
for "_i" from 1 to 2 do {_unit addItemToUniform "UK3CB_BAF_30Rnd";};
_unit addVest "TRYK_V_tacv10_OD";
for "_i" from 1 to 6 do {_unit addItemToVest "AGM_Bandage";};
for "_i" from 1 to 4 do {_unit addItemToVest "AGM_Morphine";};
for "_i" from 1 to 3 do {_unit addItemToVest "6Rnd_45ACP_Cylinder";};
_unit addItemToVest "HandGrenade";
_unit addItemToVest "Chemlight_yellow";
_unit addItemToVest "SmokeShellYellow";
for "_i" from 1 to 5 do {_unit addItemToVest "UK3CB_BAF_30Rnd";};
_unit addHeadgear "TIG";
_unit addGoggles "G_Balaclava_blk";
_unit addItem "UK3CB_BAF_30Rnd";
_unit addItem "6Rnd_45ACP_Cylinder";
_unit addWeapon "UK3CB_BAF_L22";
_unit addPrimaryWeaponItem "iansky_specterdr";
_unit addWeapon "hgun_Pistol_heavy_02_F";
_unit addWeapon "Binocular";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};







case "DOLG_S":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "45KO_u3_black_uniform";
for "_i" from 1 to 2 do {_unit addItemToUniform "AGM_Bandage";};
_unit addItemToUniform "AGM_Morphine";
for "_i" from 1 to 2 do {_unit addItemToUniform "rhs_mag_rgd5";};
for "_i" from 1 to 2 do {_unit addItemToUniform "Chemlight_red";};
_unit addItemToUniform "30Rnd_av_762x39_mag";
_unit addItemToUniform "16Rnd_9x21_Mag";
_unit addVest "TRYK_V_tacv1M_BK";
for "_i" from 1 to 2 do {_unit addItemToVest "AGM_Bandage";};
_unit addItemToVest "AGM_Morphine";
for "_i" from 1 to 2 do {_unit addItemToVest "rhs_mag_rdg2_black";};
for "_i" from 1 to 4 do {_unit addItemToVest "Chemlight_red";};
for "_i" from 1 to 2 do {_unit addItemToVest "30Rnd_av_762x39_mag";};
for "_i" from 1 to 6 do {_unit addItemToVest "16Rnd_9x21_Mag";};
_unit addHeadgear "Altyn_ch_ch";
_unit addGoggles "MEC_shemag_black";
_unit addItem "30Rnd_av_762x39_mag";
_unit addItem "16Rnd_9x21_Mag";
_unit addWeapon "arifle_av_104_2";
_unit addPrimaryWeaponItem "optic_ACO_grn_smg";
_unit addWeapon "hgun_Rook40_F";
_unit addWeapon "Binocular";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "DOLG_SN":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "45KO_u3_black_uniform";
for "_i" from 1 to 2 do {_unit addItemToUniform "AGM_Bandage";};
_unit addItemToUniform "AGM_Morphine";
for "_i" from 1 to 2 do {_unit addItemToUniform "rhs_mag_rgd5";};
_unit addItemToUniform "Chemlight_red";
for "_i" from 1 to 4 do {_unit addItemToUniform "rhs_10Rnd_762x54mmR_7N1";};
_unit addVest "TRYK_V_tacv1M_BK";
for "_i" from 1 to 4 do {_unit addItemToVest "AGM_Bandage";};
_unit addItemToVest "AGM_Morphine";
for "_i" from 1 to 2 do {_unit addItemToVest "rhs_mag_rdg2_black";};
for "_i" from 1 to 5 do {_unit addItemToVest "Chemlight_red";};
for "_i" from 1 to 2 do {_unit addItemToVest "30Rnd_9x21_Mag";};
_unit addHeadgear "H_Beret_blk";
_unit addGoggles "TRYK_TAC_EARMUFF_Gs";
_unit addItem "rhs_10Rnd_762x54mmR_7N1";
_unit addItem "30Rnd_9x21_Mag";
_unit addWeapon "rhs_weap_svds";
_unit addPrimaryWeaponItem "rhs_acc_pso1m2";
_unit addWeapon "av_kedrpp";
_unit addWeapon "Binocular";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "DOLG_AT":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "45KO_u3_black_uniform";
for "_i" from 1 to 2 do {_unit addItemToUniform "AGM_Bandage";};
_unit addItemToUniform "AGM_Morphine";
_unit addItemToUniform "30Rnd_ak_545x39_mag";
_unit addItemToUniform "16Rnd_9x21_Mag";
for "_i" from 1 to 2 do {_unit addItemToUniform "rhs_mag_rgd5";};
for "_i" from 1 to 2 do {_unit addItemToUniform "Chemlight_red";};
_unit addVest "TRYK_V_tacv1M_BK";
for "_i" from 1 to 2 do {_unit addItemToVest "AGM_Bandage";};
_unit addItemToVest "AGM_Morphine";
for "_i" from 1 to 4 do {_unit addItemToVest "30Rnd_ak_545x39_mag";};
for "_i" from 1 to 4 do {_unit addItemToVest "Chemlight_red";};
for "_i" from 1 to 2 do {_unit addItemToVest "rhs_mag_rdg2_black";};
for "_i" from 1 to 2 do {_unit addItemToVest "APERSTripMine_Wire_Mag";};
_unit addBackpack "PMC_B_Kitbag_blk";
for "_i" from 1 to 6 do {_unit addItemToBackpack "16Rnd_9x21_Mag";};
for "_i" from 1 to 2 do {_unit addItemToBackpack "APERSTripMine_Wire_Mag";};
_unit addHeadgear "Altyn_ch_ochki";
_unit addGoggles "G_Balaclava_blk";
_unit addItem "30Rnd_ak_545x39_mag";
_unit addItem "16Rnd_9x21_Mag";
_unit addWeapon "arifle_av_aksu_2";
_unit addPrimaryWeaponItem "optic_ACO_grn";
_unit addWeapon "hgun_Rook40_F";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "DOLG_MED":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "45KO_u3_black_uniform";
for "_i" from 1 to 2 do {_unit addItemToUniform "20Rnd_av_9x39mm_SP5";};
for "_i" from 1 to 2 do {_unit addItemToUniform "rhs_mag_rgd5";};
for "_i" from 1 to 3 do {_unit addItemToUniform "Chemlight_red";};
_unit addVest "TRYK_V_tacv1M_BK";
for "_i" from 1 to 2 do {_unit addItemToVest "20Rnd_av_9x39mm_SP5";};
for "_i" from 1 to 7 do {_unit addItemToVest "16Rnd_9x21_Mag";};
_unit addItemToVest "rhs_mag_rgd5";
for "_i" from 1 to 3 do {_unit addItemToVest "rhs_mag_rdg2_black";};
_unit addBackpack "PMC_B_Kitbag_blk";
for "_i" from 1 to 20 do {_unit addItemToBackpack "AGM_Bandage";};
for "_i" from 1 to 10 do {_unit addItemToBackpack "AGM_Morphine";};
for "_i" from 1 to 5 do {_unit addItemToBackpack "AGM_Epipen";};
for "_i" from 1 to 5 do {_unit addItemToBackpack "AGM_Bloodbag";};
_unit addHeadgear "Altyn_ch_ch";
_unit addGoggles "G_Bandanna_sport";
_unit addItem "20Rnd_av_9x39mm_SP5";
_unit addItem "16Rnd_9x21_Mag";
_unit addWeapon "arifle_av_asval";
_unit addWeapon "hgun_Rook40_F";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "DOLG_GR":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "45KO_u3_black_uniform";
for "_i" from 1 to 2 do {_unit addItemToUniform "AGM_Bandage";};
_unit addItemToUniform "AGM_Morphine";
_unit addItemToUniform "30Rnd_av_762x39_mag";
_unit addItemToUniform "rhs_VOG25";
for "_i" from 1 to 2 do {_unit addItemToUniform "rhs_mag_rgd5";};
for "_i" from 1 to 3 do {_unit addItemToUniform "Chemlight_red";};
_unit addVest "TRYK_V_tacv1M_BK";
for "_i" from 1 to 2 do {_unit addItemToVest "AGM_Bandage";};
_unit addItemToVest "AGM_Morphine";
for "_i" from 1 to 8 do {_unit addItemToVest "30Rnd_av_762x39_mag";};
_unit addItemToVest "16Rnd_9x21_Mag";
for "_i" from 1 to 3 do {_unit addItemToVest "Chemlight_red";};
for "_i" from 1 to 2 do {_unit addItemToVest "rhs_mag_rdg2_black";};
_unit addBackpack "PMC_B_Kitbag_blk";
for "_i" from 1 to 6 do {_unit addItemToBackpack "16Rnd_9x21_Mag";};
for "_i" from 1 to 3 do {_unit addItemToBackpack "rhs_VG40OP_red";};
for "_i" from 1 to 2 do {_unit addItemToBackpack "rhs_VOG25P";};
for "_i" from 1 to 5 do {_unit addItemToBackpack "rhs_GRD40_White";};
_unit addHeadgear "Altyn_ch_ch";
_unit addGoggles "Mask_M50";
_unit addItem "30Rnd_av_762x39_mag";
_unit addItem "rhs_VOG25";
_unit addItem "16Rnd_9x21_Mag";
_unit addWeapon "arifle_av_groza_gp";
_unit addWeapon "hgun_Rook40_F";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
_unit linkItem "TRYK_balaclava_BLACK_NV";
};

case "DOLG_AR":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "45KO_u3_black_uniform";
for "_i" from 1 to 2 do {_unit addItemToUniform "AGM_Bandage";};
_unit addItemToUniform "AGM_Morphine";
_unit addItemToUniform "16Rnd_9x21_Mag";
for "_i" from 1 to 2 do {_unit addItemToUniform "rhs_mag_rgd5";};
for "_i" from 1 to 6 do {_unit addItemToUniform "Chemlight_red";};
_unit addVest "TRYK_V_tacv1M_BK";
for "_i" from 1 to 2 do {_unit addItemToVest "AGM_Bandage";};
_unit addItemToVest "AGM_Morphine";
for "_i" from 1 to 2 do {_unit addItemToVest "rhs_100Rnd_762x54mmR";};
_unit addItemToVest "16Rnd_9x21_Mag";
for "_i" from 1 to 2 do {_unit addItemToVest "rhs_mag_rdg2_black";};
_unit addBackpack "PMC_B_Kitbag_blk";
for "_i" from 1 to 6 do {_unit addItemToBackpack "16Rnd_9x21_Mag";};
_unit addHeadgear "Altyn_ch_ochki";
_unit addGoggles "G_Bandanna_blk";
_unit addItem "rhs_100Rnd_762x54mmR";
_unit addItem "16Rnd_9x21_Mag";
_unit addWeapon "rhs_weap_pkm";
_unit addWeapon "hgun_Rook40_F";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "DOLG_F":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "45KO_u3_black_uniform";
for "_i" from 1 to 2 do {_unit addItemToUniform "AGM_Bandage";};
_unit addItemToUniform "AGM_Morphine";
for "_i" from 1 to 2 do {_unit addItemToUniform "rhs_mag_rgd5";};
_unit addItemToUniform "Chemlight_red";
for "_i" from 1 to 2 do {_unit addItemToUniform "rhs_30Rnd_762x39mm";};
_unit addVest "TRYK_V_tacv1M_BK";
for "_i" from 1 to 4 do {_unit addItemToVest "AGM_Bandage";};
for "_i" from 1 to 2 do {_unit addItemToVest "AGM_Morphine";};
_unit addItemToVest "rhs_mag_rgd5";
for "_i" from 1 to 3 do {_unit addItemToVest "rhs_mag_rdg2_black";};
for "_i" from 1 to 2 do {_unit addItemToVest "Chemlight_red";};
for "_i" from 1 to 6 do {_unit addItemToVest "16Rnd_9x21_Mag";};
for "_i" from 1 to 4 do {_unit addItemToVest "rhs_30Rnd_762x39mm";};
_unit addHeadgear "Altyn_ch_ch";
_unit addGoggles "MEC_shemag_black";
_unit addItem "rhs_30Rnd_762x39mm";
_unit addItem "16Rnd_9x21_Mag";
_unit addWeapon "rhs_weap_ak103_npz";
_unit addPrimaryWeaponItem "rhs_acc_ak5";
_unit addPrimaryWeaponItem "iansky_cmore";
_unit addWeapon "hgun_Rook40_F";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};





case "VOEN_S":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "rhs_uniform_flora_patchless_alt";
for "_i" from 1 to 2 do {_unit addItemToUniform "AGM_Bandage";};
_unit addItemToUniform "AGM_Morphine";
_unit addItemToUniform "rhs_mag_9x18_12_57N181S";
for "_i" from 1 to 2 do {_unit addItemToUniform "rhs_mag_rgd5";};
_unit addItemToUniform "Chemlight_green";
_unit addItemToUniform "rhs_mag_rdg2_white";
_unit addVest "rhs_6b13_crewofficer";
for "_i" from 1 to 2 do {_unit addItemToVest "AGM_Bandage";};
_unit addItemToVest "AGM_Morphine";
for "_i" from 1 to 4 do {_unit addItemToVest "rhs_mag_9x18_12_57N181S";};
for "_i" from 1 to 2 do {_unit addItemToVest "Chemlight_green";};
for "_i" from 1 to 3 do {_unit addItemToVest "30Rnd_ak_545x39_mag";};
_unit addHeadgear "Beret_a";
_unit addItem "30Rnd_ak_545x39_mag";
_unit addItem "rhs_mag_9x18_12_57N181S";
_unit addWeapon "arifle_av_aksu";
_unit addWeapon "rhs_weap_makarov_pmm";
_unit addWeapon "Binocular";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "VOEN_AR":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "rhs_uniform_flora_patchless_alt";
for "_i" from 1 to 2 do {_unit addItemToUniform "AGM_Bandage";};
_unit addItemToUniform "AGM_Morphine";
for "_i" from 1 to 2 do {_unit addItemToUniform "rhs_mag_9x18_12_57N181S";};
for "_i" from 1 to 2 do {_unit addItemToUniform "rhs_mag_rgd5";};
for "_i" from 1 to 2 do {_unit addItemToUniform "Chemlight_green";};
_unit addVest "rhs_6b13_6sh92";
for "_i" from 1 to 2 do {_unit addItemToVest "AGM_Bandage";};
_unit addItemToVest "AGM_Morphine";
_unit addItemToVest "rhs_100Rnd_762x54mmR";
for "_i" from 1 to 2 do {_unit addItemToVest "rhs_mag_9x18_12_57N181S";};
for "_i" from 1 to 2 do {_unit addItemToVest "rhs_mag_rdg2_white";};
_unit addBackpack "rhs_assault_umbts";
_unit addItemToBackpack "rhs_100Rnd_762x54mmR";
for "_i" from 1 to 2 do {_unit addItemToBackpack "rhs_mag_9x18_12_57N181S";};
_unit addHeadgear "H_Bandanna_mcamo";
_unit addItem "rhs_100Rnd_762x54mmR";
_unit addItem "rhs_mag_9x18_12_57N181S";
_unit addWeapon "rhs_weap_pkm";
_unit addWeapon "rhs_weap_makarov_pmm";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "VOEN_GR":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "rhs_uniform_flora_patchless_alt";
for "_i" from 1 to 2 do {_unit addItemToUniform "AGM_Bandage";};
_unit addItemToUniform "AGM_Morphine";
for "_i" from 1 to 2 do {_unit addItemToUniform "rhs_VOG25";};
for "_i" from 1 to 2 do {_unit addItemToUniform "rhs_mag_rgd5";};
for "_i" from 1 to 6 do {_unit addItemToUniform "Chemlight_green";};
_unit addVest "rhs_6b13_6sh92_vog";
for "_i" from 1 to 2 do {_unit addItemToVest "AGM_Bandage";};
_unit addItemToVest "AGM_Morphine";
for "_i" from 1 to 3 do {_unit addItemToVest "rhs_30Rnd_545x39_AK";};
_unit addItemToVest "rhs_VOG25";
for "_i" from 1 to 2 do {_unit addItemToVest "rhs_mag_rdg2_white";};
_unit addHeadgear "H_Watchcap_blk";
_unit addItem "rhs_30Rnd_545x39_AK";
_unit addItem "rhs_VOG25";
_unit addWeapon "rhs_weap_ak74m_gp25_folded";
_unit addPrimaryWeaponItem "rhs_acc_dtk";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "VOEN_MED":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "rhs_uniform_flora_patchless_alt";
_unit addItemToUniform "rhs_30Rnd_545x39_AK";
for "_i" from 1 to 3 do {_unit addItemToUniform "Chemlight_green";};
for "_i" from 1 to 2 do {_unit addItemToUniform "rhs_mag_rdg2_white";};
_unit addVest "rhs_6b13";
_unit addItemToVest "rhs_mag_9x18_12_57N181S";
_unit addItemToVest "rhs_30Rnd_545x39_AK";
_unit addBackpack "rhs_assault_umbts";
for "_i" from 1 to 20 do {_unit addItemToBackpack "AGM_Bandage";};
for "_i" from 1 to 10 do {_unit addItemToBackpack "AGM_Morphine";};
for "_i" from 1 to 5 do {_unit addItemToBackpack "AGM_Epipen";};
for "_i" from 1 to 5 do {_unit addItemToBackpack "AGM_Bloodbag";};
for "_i" from 1 to 2 do {_unit addItemToBackpack "rhs_mag_9x18_12_57N181S";};
_unit addItemToBackpack "rhs_30Rnd_545x39_AK";
_unit addHeadgear "rhs_6b26";
_unit addItem "rhs_30Rnd_545x39_AK";
_unit addItem "rhs_mag_9x18_12_57N181S";
_unit addWeapon "rhs_weap_ak74m_2mag";
_unit addPrimaryWeaponItem "rhs_acc_dtk";
_unit addWeapon "rhs_weap_makarov_pmm";
_unit addWeapon "Binocular";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "VOEN_AT":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "rhs_uniform_flora_patchless_alt";
for "_i" from 1 to 2 do {_unit addItemToUniform "AGM_Bandage";};
_unit addItemToUniform "AGM_Morphine";
_unit addItemToUniform "rhs_30Rnd_545x39_AK";
for "_i" from 1 to 2 do {_unit addItemToUniform "rhs_mag_rgd5";};
for "_i" from 1 to 4 do {_unit addItemToUniform "Chemlight_green";};
_unit addVest "rhs_6b13";
for "_i" from 1 to 2 do {_unit addItemToVest "AGM_Bandage";};
_unit addItemToVest "AGM_Morphine";
for "_i" from 1 to 2 do {_unit addItemToVest "Chemlight_green";};
_unit addItemToVest "rhs_mag_rdg2_white";
_unit addBackpack "rhs_rpg_empty";
_unit addItemToBackpack "rhs_rpg7_OG7V_mag";
for "_i" from 1 to 3 do {_unit addItemToBackpack "rhs_30Rnd_545x39_AK";};
_unit addItemToBackpack "rhs_mag_rdg2_white";
_unit addHeadgear "rhs_6b26";
_unit addItem "rhs_30Rnd_545x39_AK";
_unit addItem "rhs_rpg7_PG7VL_mag";
_unit addWeapon "rhs_weap_ak74m";
_unit addPrimaryWeaponItem "rhs_acc_dtk";
_unit addWeapon "rhs_weap_rpg7";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "VOEN_SN":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "rhs_uniform_flora_patchless_alt";
for "_i" from 1 to 2 do {_unit addItemToUniform "AGM_Bandage";};
_unit addItemToUniform "AGM_Morphine";
for "_i" from 1 to 2 do {_unit addItemToUniform "rhs_10Rnd_762x54mmR_7N1";};
for "_i" from 1 to 2 do {_unit addItemToUniform "rhs_mag_rgd5";};
for "_i" from 1 to 4 do {_unit addItemToUniform "Chemlight_green";};
_unit addVest "rhs_vydra_3m";
for "_i" from 1 to 2 do {_unit addItemToVest "AGM_Bandage";};
_unit addItemToVest "AGM_Morphine";
for "_i" from 1 to 2 do {_unit addItemToVest "rhs_10Rnd_762x54mmR_7N1";};
for "_i" from 1 to 5 do {_unit addItemToVest "rhs_mag_9x18_12_57N181S";};
for "_i" from 1 to 2 do {_unit addItemToVest "rhs_mag_rdg2_white";};
_unit addHeadgear "H_Bandanna_mcamo";
_unit addItem "rhs_10Rnd_762x54mmR_7N1";
_unit addItem "rhs_mag_9x18_12_57N181S";
_unit addWeapon "rhs_weap_svdp_wd";
_unit addPrimaryWeaponItem "rhs_acc_pso1m2";
_unit addWeapon "rhs_weap_makarov_pmm";
_unit addWeapon "Binocular";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};

case "VOEN_F":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "rhs_uniform_flora_patchless_alt";
for "_i" from 1 to 2 do {_unit addItemToUniform "AGM_Bandage";};
_unit addItemToUniform "AGM_Morphine";
for "_i" from 1 to 2 do {_unit addItemToUniform "rhs_mag_rgd5";};
_unit addItemToUniform "Chemlight_green";
_unit addItemToUniform "SmokeShellGreen";
_unit addItemToUniform "rhs_30Rnd_545x39_AK";
_unit addVest "rhs_6b13_6sh92";
for "_i" from 1 to 4 do {_unit addItemToVest "AGM_Bandage";};
for "_i" from 1 to 2 do {_unit addItemToVest "AGM_Morphine";};
_unit addItemToVest "rhs_mag_9x18_12_57N181S";
for "_i" from 1 to 4 do {_unit addItemToVest "rhs_30Rnd_545x39_AK";};
_unit addHeadgear "rhs_6b26_ess";
_unit addItem "rhs_30Rnd_545x39_AK";
_unit addItem "rhs_mag_9x18_12_57N181S";
_unit addWeapon "rhs_weap_ak74m";
_unit addPrimaryWeaponItem "rhs_acc_dtk";
_unit addWeapon "rhs_weap_makarov_pmm";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
};





case "UCHONY_1":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "TRYK_OVERALL_SAGE_BLKboots_nk_blk2";
for "_i" from 1 to 2 do {_unit addItemToUniform "UK3CB_BAF_30Rnd";};
for "_i" from 1 to 5 do {_unit addItemToUniform "Chemlight_green";};
_unit addVest "LOP_V_Carrier_OLV";
for "_i" from 1 to 6 do {_unit addItemToVest "AGM_Bandage";};
for "_i" from 1 to 4 do {_unit addItemToVest "AGM_Morphine";};
for "_i" from 1 to 2 do {_unit addItemToVest "rhs_mag_9x19_17";};
_unit addItemToVest "UK3CB_BAF_30Rnd";
_unit addHeadgear "H_PilotHelmetHeli_B";
_unit addGoggles "Mask_M40";
_unit addItem "UK3CB_BAF_30Rnd";
_unit addItem "rhs_mag_9x19_17";
_unit addWeapon "UK3CB_BAF_L85A2_RIS";
_unit addPrimaryWeaponItem "UK3CB_BAF_L85_Silencer";
_unit addPrimaryWeaponItem "UK3CB_BAF_LLM_Flashlight";
_unit addPrimaryWeaponItem "iansky_specterdr";
_unit addWeapon "rhs_weap_pya";
_unit addWeapon "Binocular";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
_unit linkItem "TRYK_Shemagh_shade_G_N";
};

case "UCHONY_2":{
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform "TRYK_OVERALL_nok_flesh";
for "_i" from 1 to 3 do {_unit addItemToUniform "UK3CB_BAF_30Rnd";};
for "_i" from 1 to 5 do {_unit addItemToUniform "Chemlight_green";};
_unit addVest "LOP_V_Carrier_TAN";
_unit addItemToVest "rhs_mag_9x19_17";
for "_i" from 1 to 2 do {_unit addItemToVest "UK3CB_BAF_30Rnd";};
_unit addBackpack "B_Carryall_cbr";
for "_i" from 1 to 30 do {_unit addItemToBackpack "AGM_Bandage";};
for "_i" from 1 to 20 do {_unit addItemToBackpack "AGM_Morphine";};
for "_i" from 1 to 16 do {_unit addItemToBackpack "AGM_Epipen";};
for "_i" from 1 to 10 do {_unit addItemToBackpack "AGM_Bloodbag";};
for "_i" from 1 to 2 do {_unit addItemToBackpack "UK3CB_BAF_30Rnd";};
_unit addHeadgear "H_PilotHelmetHeli_B";
_unit addGoggles "Mask_M40";
_unit addItem "UK3CB_BAF_30Rnd";
_unit addItem "rhs_mag_9x19_17";
_unit addWeapon "UK3CB_BAF_L85A2_RIS";
_unit addPrimaryWeaponItem "UK3CB_BAF_L85_Silencer";
_unit addPrimaryWeaponItem "UK3CB_BAF_LLM_Flashlight";
_unit addPrimaryWeaponItem "iansky_specterdr";
_unit addWeapon "rhs_weap_pya";
_unit addWeapon "Binocular";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
_unit linkItem "TRYK_Shemagh_shade_WH_N";
};



		default { diag_log [ "stalker.sqf error: NO TEMPLATE " , _tpl ]; };
	};
};


[_unit, _tpl] call _fn_checktpl;